### PR TITLE
Manual testing frame for more scenarios and updated dictionary

### PR DESCRIPTION
**Pull request by BogdanRandstad**
## Description

Manual testing for negative responses. I tested all the possible negative responses. Currently The testable negative responses are: RequestOutOfRange, SubfunctionNotSupported and IncorrectMessageLengthOrInvalidFormat. You could see on the trello link attachment a screenshot with negative responses on MCU logs. Also I updated the dictionary from python with a missed negative response from backend functionalities.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Capture

### CODE REVIEW

**Review by Mihnea9901 — CHANGES_REQUESTED** [review]
Really?
You tested something we knew it was working for a few sprints by now. It took you 3 days to add a new line.
You were supposed to make scenarios on the rest_api part, in which you send different requests for different services and you expect different negative responses to be received.

**Comment by TheoRandstad** [comment]
I think you misunderstoond the task. You just ran the MCU with 2 examples(those were shown to you also) when all services have handle for nrcs. Anyway, you cant have a PR with just one line..And put screenshots from backend..

**Review by CatalinGP — CHANGES_REQUESTED** [review]
The task name is "Negative responses scenarios for existing SID's"

The NRC scenarios are documented into the following document:
https://docs.google.com/document/d/1ZBCEYmZyT3Js3zB7Ijt3QLMRzK6hnvEI/edit?usp=sharing&ouid=101402619014143826430&rtpof=true&sd=true

Manual testing is part of validating of implemented code.

**Review by asavu91 — CHANGES_REQUESTED** [review]
The task involved implementing scenarios directly in the API code, similar to how it's done in lines 61-76 of manual_send_frame.py in the API directory, rather than just focusing on testing.

**Pull request closed without merging**
